#application-local properties file

paypal.oauth.url= https://api-m.sandbox.paypal.com/v1/oauth2/token

paypal.client.id=  ${P_CLIENT_ID}

paypal.secret.id=  ${P_SECRET_ID}

paypal.create-order.url=https://api-m.sandbox.paypal.com/v2/checkout/orders



