spring.application.name=PayPalProviderMicroService
#providing the embedded tomcat server port no
server.port =7057

paypal.oauth.url= https://api-m.sandbox.paypal.com/v1/oauth2/token

paypal.client.id= ${P_CLIENT_ID}

paypl.secret.id=  ${P_SECRET_ID}

